-- MySQL Script generated by MySQL Workbench
-- Sat Sep 30 18:51:07 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema homework2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema homework2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `homework2` DEFAULT CHARACTER SET utf8 ;
USE `homework2` ;

-- -----------------------------------------------------
-- Table `homework2`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homework2`.`Student` (
  `StudentID` VARCHAR(10) NOT NULL,
  `FirstName` VARCHAR(20) NOT NULL,
  `LastName` VARCHAR(20) NOT NULL,
  `Department` VARCHAR(45) NOT NULL,
  `GPA` FLOAT NOT NULL DEFAULT 0.00,
  `Gender` ENUM('Male', 'Female') NOT NULL,
  PRIMARY KEY (`StudentID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homework2`.`Faculty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homework2`.`Faculty` (
  `FacultyID` VARCHAR(10) NOT NULL,
  `FirstName` VARCHAR(20) NOT NULL,
  `LastName` VARCHAR(20) NOT NULL,
  `Department` VARCHAR(45) NOT NULL,
  `Gender` ENUM('Male', 'Female') NOT NULL,
  `Title` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`FacultyID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homework2`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homework2`.`Course` (
  `CourseID` VARCHAR(20) NOT NULL,
  `Section` INT NOT NULL,
  `InstructorID` VARCHAR(10) NULL,
  `Time` TIME(1) NULL,
  `Classroom` VARCHAR(45) NULL DEFAULT NULL,
  `Capacity` INT NULL DEFAULT 100,
  PRIMARY KEY (`CourseID`, `Section`),
  INDEX `fk_Course_Faculty_idx` (`InstructorID` ASC),
  CONSTRAINT `Faculty`
    FOREIGN KEY (`InstructorID`)
    REFERENCES `homework2`.`Faculty` (`FacultyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homework2`.`Enrollment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homework2`.`Enrollment` (
  `StudentID` VARCHAR(10) NOT NULL,
  `CourseID` VARCHAR(20) NOT NULL,
  `Section` INT NOT NULL,
  `State` ENUM('enrolled', 'waitlisted', 'completed') NOT NULL,
  `Grade` ENUM('A+', 'A', 'B', 'C', 'D', 'F') NULL DEFAULT NULL,
  PRIMARY KEY (`Section`, `CourseID`, `StudentID`),
  INDEX `StudentID_idx` (`StudentID` ASC),
  INDEX `CourseID_idx` (`CourseID` ASC),
  CONSTRAINT `StudentID`
    FOREIGN KEY (`StudentID`)
    REFERENCES `homework2`.`Student` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CourseID`
    FOREIGN KEY (`CourseID`)
    REFERENCES `homework2`.`Course` (`CourseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `homework2`;

DELIMITER $$
USE `homework2`$$
CREATE DEFINER = CURRENT_USER TRIGGER `homework2`.`Student_BEFORE_INSERT` BEFORE INSERT ON `Student` FOR EACH ROW
BEGIN
	IF (NEW.LastName = 'Zhang') AND (NEW.FirstName = 'Shenzhi') AND (NEW.GPA > 2.7) THEN
		SIGNAL SQLSTATE '12345';
	END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
