-- MySQL Script generated by MySQL Workbench
-- Fri Sep 29 21:35:20 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema homework2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema homework2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `homework2` DEFAULT CHARACTER SET utf8 ;
USE `homework2` ;

-- -----------------------------------------------------
-- Table `homework2`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homework2`.`Student` (
  `studentID` VARCHAR(10) NOT NULL,
  `FirstName` VARCHAR(20) NOT NULL,
  `LastName` VARCHAR(20) NOT NULL,
  `Department` VARCHAR(45) NOT NULL,
  `IQ` INT NOT NULL,
  `Gender` ENUM('Male', 'Female') NOT NULL,
  PRIMARY KEY (`studentID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homework2`.`Faculty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homework2`.`Faculty` (
  `FacultyID` VARCHAR(10) NOT NULL,
  `FirstName` VARCHAR(20) NOT NULL,
  `LastName` VARCHAR(20) NOT NULL,
  `Department` VARCHAR(45) NOT NULL,
  `Gender` ENUM('Male', 'Female') NOT NULL,
  `Title` VARCHAR(45) NULL,
  PRIMARY KEY (`FacultyID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homework2`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homework2`.`Course` (
  `CourseID` VARCHAR(20) NOT NULL,
  `Section` INT NOT NULL,
  `Time` TIME(4) NULL,
  `Classroom` VARCHAR(45) NULL,
  `Capacity` INT NULL,
  PRIMARY KEY (`CourseID`, `Section`),
  CONSTRAINT `InstructorID`
    FOREIGN KEY ()
    REFERENCES `homework2`.`Faculty` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homework2`.`Enrollment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homework2`.`Enrollment` (
  `State` ENUM('enrolled', 'waitlist') NOT NULL,
  CONSTRAINT `StudentID`
    FOREIGN KEY ()
    REFERENCES `homework2`.`Student` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CourseID`
    FOREIGN KEY ()
    REFERENCES `homework2`.`Course` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Section`
    FOREIGN KEY ()
    REFERENCES `homework2`.`Course` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `homework2`;

DELIMITER $$
USE `homework2`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`student_BEFORE_INSERT` BEFORE INSERT ON `student` FOR EACH ROW
BEGIN
	IF (NEW.LastName = 'Zhang') AND (NEW.FirstName = 'Shenzhi') AND (NEW.IQ > 100) THEN
		SIGNAL SQLSTATE '12345';
	END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
